### ISSUE TITLE
dependency on retiring spatial infrastructure packages

### ISSUE THREAD

**Issue by rsbivand** [PabloCapilla/incR#3]
You will be aware, for example from:
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html,
https://r-spatial.org/r/2023/04/10/evolution3.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and 
perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1 
that `rgdal`, `rgeos` and `maptools` will be retired this
year, in October 2023. 

'maptools', 'rgeos' are imported, but only `maptools::crepuscule` is found by `pkgapi`, not in NAMESPACE, lines 131 and 136 in R/inRt.R. Please follow up on emails that you have received, and fix best by June, latest October 2023.

**Comment by PabloCapilla** [comment]
This has now been sorted in version 2.1.0
